### ISSUE TITLE
The admin email box is not visisble until we enable it and save the settings and refresh the page

### ISSUE THREAD

**Issue by kavya-cedcoss** [Makewebbetter/mwb-cf7-integration-with-zoho-crm#22]
![screenshot-localhost_10034-2021 09 28-10_45_40 (1)](https://user-images.githubusercontent.com/63343498/135027526-4627f718-703e-42c5-b0a8-c9695798f4af.png)

**Comment by brijmohan-cedcoss** [comment]
Fixed
