### ISSUE TITLE
Issue with "View logs" link

### ISSUE THREAD

**Issue by kavya-cedcoss** [Makewebbetter/mwb-cf7-integration-with-zoho-crm#23]
If we click on view log, we are getting error.
![screenshot-localhost_10034-2021 09 28-12_28_58 (1)](https://user-images.githubusercontent.com/63343498/135038631-46d8bf0f-0d27-4047-8c21-827d856beeef.png)

![screenshot-localhost_10034-2021 09 28-12_29_10 (1)](https://user-images.githubusercontent.com/63343498/135038642-a43aea0f-15a0-422e-ba41-033f8971124e.png)

**Comment by brijmohan-cedcoss** [comment]
Fixed
