### ISSUE TITLE
Issue with app setup guide

### ISSUE THREAD

**Issue by kavya-cedcoss** [Makewebbetter/mwb-cf7-integration-with-zoho-crm#24]
The visbility is extra large and going out of the screen
![screenshot-localhost_10034-2021 09 28-12_59_46](https://user-images.githubusercontent.com/63343498/135043024-86db9d89-9a3b-482a-b486-dc94cff0bdb8.png)
![screenshot-localhost_10034-2021 09 28-13_00_00](https://user-images.githubusercontent.com/63343498/135043032-98170cea-36df-4f75-9ee0-e44b22937a49.png)
.

**Comment by brijmohan-cedcoss** [comment]
Fixed
