### ISSUE TITLE
Issue with   syncing of forms

### ISSUE THREAD

**Issue by kavya-cedcoss** [Makewebbetter/mwb-cf7-integration-with-zoho-crm#25]
None of the forms are syncing, it's saying there has been critical error on site
![screenshot-nimbus-capture-2021 09 28-14_46_37 (1)](https://user-images.githubusercontent.com/63343498/135059904-dd25da33-d01a-4100-bfed-75c601c78a4b.png)
.

**Comment by brijmohan-cedcoss** [comment]
Fixed
